### PR TITLE
No Updating for design, when switching binary_iv to other designs 

### PR DESCRIPTION
**Pull request by zerinahuang**
if you load `binary_iv design` in the design tab firstly, then switch to `block_cluster_two_arm design`.

The problems:
- The design name doesn't change 

- no summary 

- no code output 

- no error/warning to detect why there is no summary and code output

The reason I supposed is that the values of arguments are inherited from the previous loaded design.
e.g The common arguments' name of `binary_iv design` and `block_cluster_two_arm design` are `N`, `assignment probs`. 

The default value of `assignment probs` in `binary_iv design` is c(0.5,0.5,0.5,0.5), which also are appeared when you load `block_cluster_two_arm design`. Even though in the initial case of `block_cluster_two_arm design` we don't need the value of `assignment probs`.

The problems also happen when you switch to other designs, and those designs have common arguments' names.

### CODE REVIEW

**Comment by internaut** [comment]
Thanks for that, @zerinahuang, but could you elaborate a little bit on what problem this patch solves and how it does that? This helps me while testing, thanks.

**Comment by zerinahuang** [comment]
sorry, I updated the description

**Comment by internaut** [comment]
Okay, thanks.

I had a quick look. The problem with switching the designers seems fixed, however, another problem is introduced: Load a designer, e.g. Two Arm, try changing a parameter, e.g. N to 99, and the parameter always is immediately reset its default value (100). Didn't have the time to look what's causing this.

**Comment by zerinahuang** [comment]
Sure, I'll check it out, Thanks for your review.

**Comment by zerinahuang** [comment]
@internaut fixed it! Thank you.

**Comment by internaut** [comment]
Thanks, @zerinahuang, this indeed fixes the mentioned problem.

However, switching between "block cluster two arm" and "cluster sampling" still causes problems, because the value for `N_i_in_cluster` is retained while switching and hence an incompatible default value is used.

Maybe we should clear the arguments every time a design is switched and not retain any value?

**Comment by zerinahuang** [comment]
I know the conflict between `block cluster two arm `and `cluster sampling`. You're right, we should clear all the values when switching to a new designer. 

But I don't know how to detect whether the designer is switched. Especially  all of the variables about designers are reactive. Do you have any idea for this?

Thanks!

**Comment by internaut** [comment]
Ok, I'll have a look (though probably not today).

**Comment by internaut** [comment]
Hey @zerinahuang, it was indeed quite hassle to get somehow notified when the design was changed due to the crazy reactive input side-effects... anyway I think I fixed it -- could you please have a look and try it out? I also merged master into this branch.

**Comment by zerinahuang** [comment]
Hi @internaut 
I checked it out, but the conflict between` block cluster two arms `and` cluster sampling` is still there. It would be great if you double-check it. Thanks!

**Comment by internaut** [comment]
Oh well... The problem is that it takes old values from the UI. Hope this fixes it, please try it out.

**Comment by zerinahuang** [comment]
@internaut The problem between `block cluster two arms` and `cluster sampling` is fixed, but if you load `multi_arms` design, there will be error on the error/ warning panel

**Comment by internaut** [comment]
It's really problematic to determine whether the designer was just switched and to use the proper default values for the inputs then. I now implemented a little "hack" with JS that sets a `switching_designers` state while a new designer is being loaded.

Testing is also a pain. I made a more thorough test and came across some issues that I fixed on the way. Will publish a little "checklist" for testing soon.

Anyway, please test again @zerinahuang.

**Comment by internaut** [comment]
Here's the checklist btw.: https://github.com/DeclareDesign/DDWizard/blob/master/_docs/test_checklist.md

**Comment by zerinahuang** [comment]
@internaut The values of args in the design tab work well, but if you load `binary_iv` design firstly then load the `mediation analysis` designer,  The values of args in the diagnose tab will be retained from the previous designer, such as the value of `a`, `b`, `d`.

**Comment by internaut** [comment]
Couldn't reproduce this. Did you switch from "Design" to "Diagnose" tab really quickly? Maybe then this can happen. Will have a look at disabling the "Diagnose" tab while a designer is being loaded.

**Comment by internaut** [comment]
Can reproduce this now and will try to fix it.

**Comment by zerinahuang** [comment]
@internaut I tested the shiny again, The error came out when you loaded the `multi_arm` design firstly, then loaded `two_by_two` design.

> Error message: Invalid values supplied to the following arguments: outcome_means

**Comment by zerinahuang** [comment]
Sorry, my bad. I should make it clear. 

The error message is from diagnose tab. I did run the codes from the issue_195 branch.

**Comment by zerinahuang** [comment]
Yep, it works fine. You can merge into the master branch if you approve the review. Thank you.

**Comment by internaut** [comment]
Phew, that was hard work! Thanks a lot for your contributions and feedback @zerinahuang!

**Pull request merged**
