### PR TITLE
change the default format of diagnose table

### PR DESCRIPTION
**Pull request by zerinahuang**
- Put the standard deviation under the estimators 
- possible to switch the format of diagnose table as the users wish

### CODE REVIEW

**Comment by internaut** [comment]
Works well, I like it! Just one thing: Why do we need a "Confirm" button? Isn't it okay to make the table output reactive on the "Convert ..." checkbox?

**Comment by zerinahuang** [comment]
Confirm button seems like not necessary, I'll just make it reactive

**Comment by zerinahuang** [comment]
fix it!

**Comment by internaut** [comment]
Nice, merged it!

**Pull request merged**
