### PR TITLE
Aesthetics of shiny 

### PR DESCRIPTION
**Pull request by zerinahuang**
I didn't change the theme, only changed the color of buttons, same as [declare design](https://declaredesign.org) and add the icon on the left-top.

### CODE REVIEW

**Comment by internaut** [comment]
I like the new style! @macartan should have a look and tell if that's what he wants since he requested that change.

Regarding the code: This is a perfect use-case for CSS, Sisi. That's why I added CSS in `custom.css` and reverted the changes to the individual buttons. Using this, we don't have to adjust every single button (and new buttons we might later add), but can change their look globally via CSS.

**Comment by zerinahuang** [comment]
That's cool, thanks for your @internaut comments, learn something new!

> I like the new style! @macartan should have a look and tell if that's what he wants since he requested that change.
> 
> Regarding the code: This is a perfect use-case for CSS, Sisi. That's why I added CSS in `custom.css` and reverted the changes to the individual buttons. Using this, we don't have to adjust every single button (and new buttons we might later add), but can change their look globally via CSS.

**Comment by internaut** [comment]
No objections until now from @macartan so I'll merge these changes.

**Comment by macartan** [comment]
I was looking at the wrong branch and couldnt see the changes
this looks fabulous

@Markus Konrad <markus.konrad@wzb.eu>  would it make sense to get this onto
the server now in prep for sharing?

**Pull request merged**
